# Generated by Django 4.2.7 on 2023-12-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_user_is_sick'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-updated', '-username']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
