# Generated by Django 4.2.7 on 2023-12-12 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_user_is_boss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='location',
        ),
        migrations.RemoveField(
            model_name='department',
            name='max_users',
        ),
        migrations.RemoveField(
            model_name='department',
            name='staff',
        ),
    ]
